# Generated by Django 5.0.7 on 2025-08-13 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entreprise', models.CharField(max_length=255)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type_titre', models.CharField(choices=[('licence_type_1', 'Licence de type 1'), ('licence_type_2', 'Licence de type 2'), ('agrement_vendeurs', 'Agrément vendeurs'), ('agrement_installateurs', 'Agrément installateurs'), ('concessions', 'Concessions'), ('recepisse', 'Récépissé')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('motivations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('soumise', 'Soumise'), ('en_examen', 'En examen'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('numero_dossier', models.CharField(blank=True, max_length=100, null=True)),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('commentaires_admin', models.TextField(blank=True, null=True)),
                ('documents_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
