# Generated by Django 5.0.7 on 2025-08-13 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_titre', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('licence_type_1', 'Licence de type 1'), ('licence_type_2', 'Licence de type 2'), ('agrement_vendeurs', 'Agrément vendeurs'), ('agrement_installateurs', 'Agrément installateurs'), ('concessions', 'Concessions'), ('recepisse', 'Récépissé')], max_length=50)),
                ('entreprise_nom', models.CharField(max_length=255)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('duree_ans', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions_specifiques', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
